# .nosana-ci.yml
nosana:
  description: Build, Test and Deploy dApps!

global:
  image: node
  trigger:
    push:
      branches:
        - main

jobs:
  - name: build
    commands:
      - echo "building..."
      - npm ci
      - npm run compile
    artifacts:
      - name: node_modules
        path: .

  - name: test
    environment:
      REPORT_GAS: "true"
    commands:
      - echo "testing..."
      - npm run test
    resources:
      - name: node_modules

  - name: deploy
    secrets:
      - PRIVATE_KEY
    commands:
      - echo "deploying..."
      - npm run deploy
    resources:
      - name: node_modules
